# Generated by Django 4.2 on 2024-07-01 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('authentication', '0007_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academic.batch'),
            preserve_default=False,
        ),
    ]
